FROM bitnami/moodle:5.0.1

ENV MOODLE_DATABASE_TYPE=mysqli
ENV MOODLE_DATABASE_HOST=turntable.proxy.rlwy.net
ENV MOODLE_DATABASE_PORT_NUMBER=48014
ENV MOODLE_DATABASE_NAME=railway
ENV MOODLE_DATABASE_USER=root
ENV MOODLE_DATABASE_PASSWORD=WXnHQtLLhrfFVcTmXzqkSJDeLSvbuTPP

ENV MOODLE_USERNAME=admin
ENV MOODLE_PASSWORD=Admin123!
ENV MOODLE_EMAIL=admin@example.com
ENV MOODLE_SITE_NAME="Magic Moodle"
ENV MOODLE_SKIP_INSTALL=no

ENV APACHE_HTTP_PORT_NUMBER=8080
ENV APACHE_DISABLE_REWRITE=1
ENV MOODLE_ENABLE_HTTPS=no
